{{ if .Values.jupyter.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-jupyter
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: jupyter
spec:
  replicas: {{ .Values.jupyter.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: jupyter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: jupyter
    spec:
      imagePullSecrets:
        {{- toYaml .Values.jupyter.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "dask.fullname" . }}-jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          {{- if .Values.jupyter.args }}
          args:
            {{- toYaml .Values.jupyter.args | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8888
          resources:
            {{- toYaml .Values.jupyter.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/jovyan/.jupyter
          {{- if .Values.comm.tls }}
            - name: {{ template "dask.fullname" . }}-client-tls-volume
              mountPath: /etc/dask/client/tls/
              readOnly: true
            - name: {{ template "dask.fullname" . }}-client-ca-volume
              mountPath: /etc/dask/ca/
              readOnly: true
          {{- end }}
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: {{ template "comm.protocol" . }}://{{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.comm.tls }}
            - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__KEY
              value: /etc/dask/client/tls/tls.key
            - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__CERT
              value: /etc/dask/client/tls/tls.crt
            - name: DASK_DISTRIBUTED__COMM__TLS__CA_FILE
              value: /etc/dask/ca/ca.pem
          {{- end }}
          {{- if .Values.jupyter.env }}
            {{- toYaml .Values.jupyter.env | nindent 12 }}
          {{- end }}
      nodeSelector:
        {{- toYaml .Values.jupyter.nodeSelector | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "dask.fullname" . }}-jupyter-config
      {{- if .Values.comm.tls }}
        - name: {{ template "dask.fullname" . }}-client-tls-volume
          secret:
            secretName: {{ .Values.comm.client.secretName }}
        - name: {{ template "dask.fullname" . }}-client-ca-volume
          secret:
            secretName: {{ .Values.comm.ca.secretName }}
      {{- end }}
    {{- with .Values.jupyter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jupyter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jupyter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
