apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.worker.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "dask.fullname" . }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
            - {{ .Values.worker.image.dask_worker }}
            - {{ template "comm.protocol" . }}://{{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.worker.resources.limits }}
            - --nthreads
            - {{ .Values.worker.resources.limits.cpu | default .Values.worker.default_resources.cpu | quote }}
            - --memory-limit
            - {{ .Values.worker.resources.limits.memory | default .Values.worker.default_resources.memory | quote }}
          {{- end }}
            - --no-dashboard
          {{- if .Values.comm.tls}}
            - --tls-ca-file
            - /etc/dask/ca/ca.pem
            - --tls-cert
            - /etc/dask/worker/tls/tls.crt
            - --tls-key
            - /etc/dask/worker/tls/tls.key
          {{- end }}
          ports:
            - containerPort: 8789
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            {{- toYaml .Values.worker.env | nindent 12 }}
        {{- if .Values.comm.tls}}
          volumeMounts:
            - name: {{ template "dask.fullname" . }}-worker-ca-volume
              mountPath: /etc/dask/ca
              readOnly: true
            - name: {{ template "dask.fullname" . }}-worker-tls-volume
              mountPath: /etc/dask/worker/tls
              readOnly: true
        {{- end }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.comm.tls }}
      volumes:
        - name: {{ template "dask.fullname" . }}-worker-tls-volume
          secret:
            secretName: {{ .Values.comm.worker.secretName}}
        - name: {{ template "dask.fullname" . }}-worker-ca-volume
          secret:
            secretName: {{ .Values.comm.ca.secretName}}
    {{- end }}
