apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: scheduler
    spec:
      imagePullSecrets:
        {{- toYaml .Values.scheduler.image.pullSecrets | nindent 8 }}
      containers:
        - name: {{ template "dask.fullname" . }}-scheduler
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          args:
            - dask-scheduler
            - --port
            - "{{ .Values.scheduler.servicePort }}"
            - --bokeh-port
            - "8787"
          {{- if .Values.comm.tls}}
            - --tls-ca-file
            - /etc/dask/ca/ca.pem
            - --tls-cert
            - /etc/dask/scheduler/tls/tls.crt
            - --tls-key
            - /etc/dask/scheduler/tls/tls.key
          {{- end }}
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          env:
            {{- toYaml .Values.scheduler.env | nindent 12 }}
      {{- if .Values.comm.tls}}
          volumeMounts:
            - name: {{ template "dask.fullname" . }}-scheduler-ca-volume
              mountPath: /etc/dask/ca
              readOnly: true
            - name: {{ template "dask.fullname" . }}-scheduler-tls-volume
              mountPath: /etc/dask/scheduler/tls
              readOnly: true
      {{- end }}
    {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.comm.tls }}
      volumes:
        - name: {{ template "dask.fullname" . }}-scheduler-tls-volume
          secret:
            secretName: {{ .Values.comm.scheduler.secretName}}
        - name: {{ template "dask.fullname" . }}-scheduler-ca-volume
          secret:
            secretName: {{ .Values.comm.ca.secretName}}
    {{- end }}
